name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # O la rama que uses para producción, ej. master, prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate de que coincida con tu entorno de desarrollo

      - name: Install Dependencies and Build Project
        run: npm ci && npm run build
        env:
          # Si necesitas variables de entorno en el build, agrégalas aquí
          # NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          # ... etc.
          CI: false # A veces necesario para evitar que las advertencias se traten como errores

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live # Opcional: si usas canales de vista previa
          projectId: 'anmlgym-e7c12' # ProjectId especificado
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels # Habilita el uso de canales si es necesario
